# Profile section
profile:
  first_name: Yee Yang
  last_name: Tee
  # picture: https://rodolfoferro.xyz/assets/images/profile.jpg   # Hosted picture
  picture: static/img/avatar.jpg  # Local picture
  contact:
    address_one: NTU
    address_two: Singapore
    phone: 
  email: yeeyang.tee@ntu.edu.sg
  description: >
    An experienced Co-Founder with a strong Engineering background. PhD candidate in Deep Learning and Vision.
    Aspiring baller. Part-time crypto geek.

# Social section
social:
  website: https://yeeyangtee.com
  github: https://github.com/coranium/
  twitter: https://twitter.com/teeyeeyang/
  linkedin: https://www.linkedin.com/in/teeyeeyang/
  facebook:
  dev: 
  medium: https://medium.com/@teeyeeyang


# Experience section
experience:
  item0:
    position: Research Associate
    company: Nanyang Technological University
    from: Aug 2020
    to: Present
    description: >
      Pioneer batch of Nanyang-DSO Graduate Programme.
    link: https://temasek-labs.ntu.edu.sg/Research/grant-call/Pages/NDGP2020.aspx
  item1:
    position: Co-Founder
    company: inspections.ai
    from: Jan 2020
    to: Present
    description: >
      Spearhead all technical development to deliver pilot projects. Develop Visual AI models mainly for construction sector.
      Liaise with clients and potential investors.
    link: http://inspections.ai
  item2:
    position: Dive Management Associate
    company: Asia Dive Academy
    from: Jan 2016
    to: Aug 2016
    description: >
      Managed operations, logistics and online platforms for dive shops. Attained professional scuba diving certification (PADI Divemaster).
    link: https://ada.asia/


# Education section
education:
  item1:
    institution: Nanyang Technological University
    program: Doctor of Philosophy
    description: Research focus - Deep Learning and Artificial Intelligence
    from: Aug 2020
    to: Present
  item2:
    institution: Nanyang Technological University
    program: Bachelor of Engineering
    description: Major in Electrical and Electronics Engineering
    from: Aug 2016
    to: Aug 2020


# Community section:
community:
  item1:
    institution: Tee Supply
    program: Community Building
    description: Assist in daily chores and revenue generation.
    from: Dec 1995
    to: Present
  item2:
    institution: NTU EEE Outreach
    program: Outreach Ambassador
    description: Entice potential students to pursue a degree in NTU, EEE. 'One Degree, A World of Opportunity.'
    from: Jan 2018
    to: Aug 2020


# Skills section
tools:
  # Consider that the following are fa icons:
  #   https://fontawesome.com/icons?d=gallery&s=brands
  - python
  - github
  - google
  - google-drive
  - markdown
  - html5

extra_skills:
  - Web scraping, data mining
  - Financial Data analysis with machine learning
  - Deep Learning and Computer Vision (PyTorch, Tensorflow, OpenCV)
  - Data Science, Analytics and Visualisation (NumPy, pandas, scikit, seaborn)


# Projects section
projects:
  item1:
    title: flask-resume-template
    subtitle: A resume template built with Flask
    description: An easy-to-configure simple resume template built with Flask and Bootstrap.
    link: https://flask-resume-template.glitch.me
    github: https://github.com/RodolfoFerro/flask-resume-template/
    img: flask-resume-template.png
    tags: [Flask, Python, Bootstrap]


